### ISSUE TITLE
Field properties in forms

### ISSUE THREAD

**Issue by egorf** [mbr/flask-bootstrap#100]
Hello!
This is more of a question, than an issue.
I am using flask-bootstrap to build a small form. 

How can I add properties, like field size to form fields?
`{{ wtf.form_field(form.key) }}` adding size here will return an error

Also, how can I hide the tag value for the field?
Thank you!

**Comment by mbr** [comment]
Changing the actual widgets is something that is in the realm of WTForms, not Flask-Bootstrap. WTForms creates Forms using _Fields_, which are then rendered using _Widgets_. Flask-Bootstrap only takes these widgets and calls them (putting a few Boostrap-specific tags around them).

Please check the WTForms docs for these things.
