### ISSUE TITLE
Text() in Navbar()?

### ISSUE THREAD

**Issue by ser** [mbr/flask-bootstrap#105]
Why it is not possible to do render text directly in ```Navbar()```?
```
def top_nav():
    return Navbar(
        View('TopItUp', 'frontend.index'),
        Text('BlaBla'),
   )
```
```
RuntimeError: Cannot render label outside Subgroup
```
It would be very useful to have this, also ```Link()``` etc., not only in ```Subgroup()```

**Comment by mbr** [comment]
``Link`` should work outside of ``Subgroup``. If I remember correctly, having just text in the navbar is not well supported by Bootstrap, but I may be wrong. If you can provide example HTML on how the end result should look, I think it could be added.

**Comment by ser** [comment]
hi, yes, it is not well documented, but available in examples. Hint: ```navbar-text``` class.
'''
<p class="navbar-text">Logged in as User</p> 
'''
It would be useful to have it, IMHO.
