### ISSUE TITLE
Add custom class attributes to navigation bar

### ISSUE THREAD

**Issue by Coxious** [mbr/flask-bootstrap#111]
I'm a beginner for front end developing, I used flask-bootstrap and flask-nav to generate the navigation bar, and I would like to use `<nav class="navbar navbar-inverse navbar-fixed-top">` instead of `<nav class="navbar navbar-default">`  generated by the render, how can I achieve that? 

I read the code and found this 
```python
    def visit_Navbar(self, node):
        kwargs = {'_class': 'navbar'}
        kwargs.update(self.kwargs)

        cont = tags.nav(**kwargs)
        ul = cont.add(tags.ul())

        for item in node.items:
            ul.add(tags.li(self.visit(item)))

        return cont
```
Should I add something to the `kwargs` so that it would change the style? How could I do that?

Thanks a lot.

**Comment by mbr** [comment]
> I'm a beginner for front end developing, I used flask-bootstrap and flask-nav to generate the navigation bar, and I would like to use <nav class="navbar navbar-inverse navbar-fixed-top"> instead of <nav class="navbar navbar-default"> generated by the render, how can I achieve that?

In general, if you want to make any modification, it's not hard to subclass the renderer:

```python
from flask_bootstrap.nav import BootstrapRenderer

class CustomRenderer(BootstrapRenderer):
    def visit_Navbar(self, node):
        nav_tag = super(CustomRenderer, self).visit_Navbar(node)
        nav_tag['class'] += 'navbar navbar-inverse navbar-fixed-top'
        return nav_tag
```

This takes advantage of the fact that the ``BootstrapRenderer`` returns ``dominate`` objects. You could replace any sort of behavior that way. This is described in the Flask-Nav documentation at http://pythonhosted.org/flask-nav/advanced-topics.html#implementing-custom-renderers. You may want to give it a better name than ``CustomRenderer``

Once you have your custom renderer, you need to register it with the application (also from the docs above):

```python
# in the apps __init__.py

from flask_nav import register_renderer
from .nav import nav, CustomRenderer  # or wherever you put all of it

def create_app(configfile=None):
    # ....
    register_renderer(app, 'custom', CustomRenderer)
```

Now the renderer is available using the id ``custom``. If you changed ``custom`` to ``bootstrap``, you would be replacing the default renderer.

Finally, we can render our navigation with it:

```jinja2
{% block navbar %}
{{nav.frontend_top.render(renderer='custom')}}
{% endblock %}
```

Now I just have to think about whether or not I want to add the fixed/inverse options to the navbar. Any changes will only make it into the next release, so the subclassing is the way to go for you I believe for now.

**Comment by Coxious** [comment]
Thanks for the reply. I've achieved that using custom render now, but really hoping to get the fixed/inverse options in the next release, it truly makes much more convenient.  :)

**Comment by AntonBiryukovUofC** [comment]
@mbr did these changes make it into a release ? and if yes, where would that be documented ?
