### ISSUE TITLE
[question] Why 4 number for versioning?

### ISSUE THREAD

**Issue by sibeliusseraphini** [mbr/flask-bootstrap#119]
I think you should change to [Semantic Versioning](http://semver.org/)

**Comment by eleweek** [comment]
Probably because the first 3 numbers mirror bootstrap's version: http://pythonhosted.org/Flask-Bootstrap/#a-note-on-versioning

**Comment by mbr** [comment]
> Probably because the first 3 numbers mirror bootstrap's version: http://pythonhosted.org/Flask-Bootstrap/#a-note-on-versioning

Precisely. I feel it's more important to be able to easily pin a Bootstrap version than a Flask-Bootstrap version, even though it breaks semantic versioning.

**Comment by sibeliusseraphini** [comment]
thanks
