### ISSUE TITLE
How to change navbar's color?

### ISSUE THREAD

**Issue by xinqiu** [mbr/flask-bootstrap#120]
I am so sorry to ask this simple(maybe) question.  I know just a little bootstrap knowledge.I feel confused about how to change the color or the style.

`base.html`:

```
{% extends "bootstrap/base.html" %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Problem Set</a>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}
```

I add 

```
{%block head %}
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}
```
on `base.html`

and make some change on `styles.css`, also change `class="navbar navbar" ` to `class="navbar navbar-custom"`,but it can't work.

I have check the `https://github.com/mbr/flask-bootstrap/issues/111`, but it seems different with my problem.

I really sorry to ask this question.
Thanks for helping me> <

**Comment by xinqiu** [comment]
I may have solved the problem, just use `{{ super() }}`

**Comment by mbr** [comment]
I believe the canonical way would be to create a custom bootstrap CSS by extending the base .less files with your own modifications.

**Comment by xinqiu** [comment]
Thanks for helping me.
