### ISSUE TITLE
Move scripts out of content block

### ISSUE THREAD

**Issue by neilthomson** [mbr/flask-bootstrap#127]
I have a base.html which extends the modules base and I put some masthead and footer html in it so I don't have to repeat this every template:

```html
{% block body -%}
<div class="container">

            {% block masthead -%}
            <div id="masthead">
                ...
            </div>
            {%- endblock %}

            <!-- Nav and Content -->
            {{super()}}

            {% block footer -%}
            <div id="footer">
                ....
            </div>
            {%- endblock %}

</div> <!-- /container -->
{%- endblock %}
```

However the js scripts come before the footer because in the modules base.html is:
```html
<body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
    <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
```

 Making a pull request with tiny change of putting scripts after the body block, can't see how it would break existing templates?

**Comment by mbr** [comment]
I am not sure what is gained by doing so, it seems to be a different, but not necessarily better way of structuring it. The ``body`` block, like most blocks, should encompass the complete inner content of the ``<body>`` tag.

I would suggest changing your structure slightly (if I need something similar, I normally add another block like ``inner_content``; alternatively you can just copy over ``base.html`` and adapt it - it's not a taboo to do so =).

A little tamer would be just be replacing the ``body`` block and just not calling ``super()``:

```jinja
{% block body -%}
<div class="container">

            {% block masthead -%}
            <div id="masthead">
                ...
            </div>
            {%- endblock %}

            <!-- Nav and Content -->
            {% block navbar %}{% endblock %}
            {% block content %}{% endblock %}

            {% block footer -%}
            <div id="footer">
                ....
            </div>
            {%- endblock %}

</div> <!-- /container -->

{% block scripts %}
{{super()}}
{% endblock %}
{%- endblock %}
```

(I'll admit I haven't tried or done this yet, I do think that the ``super()`` call inside the ``scripts`` block will work properly.)

Does that solve your issue?

**Comment by neilthomson** [comment]
That works thanks!
