### ISSUE TITLE
CHANGES does not list 3.3.6.0 release

### ISSUE THREAD

**Issue by jeffwidman** [mbr/flask-bootstrap#139]

**Comment by mbr** [comment]
Deviating a bit from the norm, I try to only list _breaking_ changes in CHANGES - as I can't do it using semver, since the Flask-Bootstrap version is tied to the Bootstrap releases.

**Comment by jeffwidman** [comment]
Ah, makes sense. Thanks for maintaining this btw, much appreciated.

**Comment by jeffwidman** [comment]
BTW, if other start reporting similar issues, you might be able to pre-empt it by add a note to this effect at the top of the CHANGES file.

**Comment by mbr** [comment]
Done. See 9392562
