### ISSUE TITLE
Documentation Website down

### ISSUE THREAD

**Issue by swiesner** [mbr/flask-bootstrap#163]
Hi,

pytonhosted.org is down for several days (weeks?) now. It would be nice to have the documentation somewhere else for being able to access it.

**Comment by mbr** [comment]
Oops, I hadn't noticed pythonhosted.org was down. Is there any info on it
coming back up?

**Comment by RcrdBrt** [comment]
Noticed it, too. It was down for like a week but it's up again now.

**Comment by mbr** [comment]
All is good then I guess. =)
