### ISSUE TITLE
No title block in base.html

### ISSUE THREAD

**Issue by techstroke** [mbr/flask-bootstrap#50]
HI Marc, going through your extension I got stuck as to why the title block in my template was not showing , but when I checked my  base.html I found out that it does not have a title block while in the documentation and on github it's there 

https://github.com/mbr/flask-bootstrap/blob/master/flask_bootstrap/templates/bootstrap/base.html#L7

 http://pythonhosted.org/Flask-Bootstrap/basic-usage.html#available-blocks 

So , either remove that from the docs or add it to next version of this extension , Thanks for the extension !!

**Comment by birdi3** [comment]
Apologies if this is not the appropriate place to leave this but similar behavior will also be seen if the  `{{super()}}` is missing from the `{% block head %}` 

(although this was not the case above)
