### ISSUE TITLE
TypeError on using any wtf imported macros

### ISSUE THREAD

**Issue by numkem** [mbr/flask-bootstrap#59]
Hello,

Just started using flask-bootstrap and I'm very happy on how easy it is to get things done quickly and cleanly.

But I'm trying to use the macros that included with the package and I'm getting this error whenever I'm trying to use the macros

`unbound method hidden_tag() must be called with UserForm instance as first argument (got nothing instead)`

This is what Userform looks like:

``` python
from flask_wtf import Form
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email, Length


class UserForm(Form):
    username = TextField('Username', [Required()])
    password = PasswordField('Password',
                             [Required(), Length(min=8, message="The password needs to be at least 8 characters long")])
    email = TextField('Email', [Required(), Email()])
    role = BooleanField('Administrator', [Required()])
```

And I'm using it in my template like this:

``` jinja2
{% extends "base_admin.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block admin_rightcolumn %}
  {{ wtf.quick_form(form, button_map={'submit_button': 'primary'}) }}
{% endblock %}
```

Thanks!

**Comment by kiiyanatz** [comment]
Am getting this error while trying to render form 
AssertionError: Field must be unbound, not a field class
