### ISSUE TITLE
'required' field flag handling

### ISSUE THREAD

**Issue by nCrazed** [mbr/flask-bootstrap#68]
Hi Marc,

Do you plan to extend the provided macros to support the 'required' [form flag](http://wtforms.readthedocs.org/en/latest/validators.html#setting-flags-on-the-field-with-validators) set by DataRequired and InputRequired validators? 

If you don't consider it out of scope for the library's macros, I am happy to submit a PR.
The implementation that I have in mind would add another keyword attribute `required` to the quick_form and form_field macros that defaults to `False` and the result of

``` python
required and field.flags.required
```

would be passed on to the wtf's field macro which will add a `required` attribute to the input tag.

**Comment by fabionorcini** [comment]
please consider this #140 

thanks
