### ISSUE TITLE
How to make a dropdown menu using flask-bootstrap?

### ISSUE THREAD

**Issue by cyrexcyborg** [mbr/flask-bootstrap#71]
This is my starting lines of ```layout.html```

```python
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/fixes.html" as fixes %}
...
``` 

```python
{% if current_user.is_authenticated() %}
			  <li>			  		
		    	<ul class="nav navbar-nav navbar-right">
		        <li class="dropdown">                    
		        	<a class="dropdown-toggle" href="#">
		                <span></span>
		                {{ current_user.email }} <strong class="caret"></strong>
		                </a>
		            	<ul class="dropdown-menu">
		                	<li><a href="#">Your Bio Page</a></li>
		                	<li><a href="#">Settings..</a></li>
		                 	<li class="divider"></li>
		                	<li><a href=<li><a href='{{ url_for("logout") }}'>Выйти</a></li>
		                </ul>
		         </li>   
				</ul>

			 </li>
 {% endif %}
````
I'm asking, because i can't explain why my dropdown doesn't work properly.
Why bootstrap.js don't loading?

**Comment by mbr** [comment]
This usually happens if you forget a ``super()`` (which you probably haven't, seeing that that is your workaround) or if you use the wrong block (i.e. ``body`` when you should be using ``content``). Flask-bootstrap loads the javascript source at the end of the ``<body>`` block, not inside ``<head>``.

**Comment by jhyland** [comment]
Ahh yes... I was mis-using the block contents. Sorry for the misunderstanding and thank you for the great project.

**Comment by ashwinprabhukp** [comment]
This post helped me, thanks!

**Comment by holden-favour** [comment]
> This usually happens if you forget a `super()` (which you probably haven't, seeing that that is your workaround) or if you use the wrong block (i.e. `body` when you should be using `content`). Flask-bootstrap loads the javascript source at the end of the `<body>` block, not inside `<head>`.





https://muhammadprocessingjs.github.io/RDAEXW0D9ZRrlvBYMOJSc4TurGR/
