### ISSUE TITLE
Pagination with others params

### ISSUE THREAD

**Issue by spk** [mbr/flask-bootstrap#94]
Hi,
I encountered some problems with routes like:
~~~ python
@recipes.route('/categories/<title>', defaults={'page': 1})
@recipes.route('/categories/<title>/page/<int:page>')
~~~
There is no way currently to pass `title` to `render_pagination` helper for `url_for`.
I handle it like [that](https://github.com/spk/flask-recipes/blob/master/app/templates/_helpers.html#L16) in a project, but I don't think it's a clean way to do that.

**Comment by mbr** [comment]
I am not sure there's a cleaner way, sans moving all that logic out of the template (it is too much anway). b0dd5f5 handles this now, with a little extra processing (checks if endpoint has been manually specified, pulls in ``view_args`` and ``args``).

Using ``render_pagination(qry)`` inside a `/categories/SomeTitle/page/2` path should now just work. Let me know if that solves your problem.

**Comment by spk** [comment]
It work when I use:

~~~ python
{{ render_pagination(pagination, request.endpoint, args={ 'title': title }) }}
~~~
But fail with only `render_pagination(pagination)`, I'm having this error:
~~~
BuildError: ('recipes.recipes_by_category', {'page': 2}, None)
...
File "/usr/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/pagination.html", line 36, in template
<li><a href="{{_arg_url_for(endpoint, url_args, page=page)}}">{{page}}</a></li>
File "/usr/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/pagination.html", line 7, in template
{{url_for(endpoint, **kargs)}}
~~~
It solve partially my problem, since I don't have to use my custom `render_pagination`.

**Comment by mbr** [comment]
When you get the error, what is title set to?

**Comment by spk** [comment]
I can copy/paste the interactive console:

~~~
File "/code/flask-bootstrap/flask_bootstrap/templates/bootstrap/pagination.html", line 36, in template
<li><a href="{{_arg_url_for(endpoint, url_args, page=page)}}">{{page}}</a></li>
~~~

~~~ python
[console ready]
>>> request
<Request 'http://localhost:5000/categories/Vegetarian' [GET]>
>>> request.view_args
{'page': 1, 'title': u'Vegetarian'}
>>> endpoint
'recipes.recipes_by_category'
>>> url_args
{}
>>> page
2
~~~

Maybe it's `url_args` that should not be blank ?

**Comment by spk** [comment]
With this change, it work for me, but I'm not sure about the other updates...

~~~ diff
diff --git a/flask_bootstrap/templates/bootstrap/pagination.html b/flask_bootstrap/templates/bootstrap/pagination.html
index 7947578..02d30e3 100644
--- a/flask_bootstrap/templates/bootstrap/pagination.html
+++ b/flask_bootstrap/templates/bootstrap/pagination.html
@@ -19,7 +19,7 @@
 -%}
 {# poor man's "do": #}
 {% with url_args = {},
-        _ = url_args.update(request.view_args if not endpoint else {}),
+        _ = url_args.update(request.view_args if endpoint else {}),
         __ = url_args.update(request.args if not endpoint else {}),
         ___ = url_args.update(args) %}
 {% with endpoint = endpoint or request.endpoint %}
~~~

**Comment by mbr** [comment]
Hmm, it is working as intended. I'm guessing you're calling you are calling ``render_pagination`` with a not-``None`` endpoint?

Generally, if you want to use the same endpoint for the pagination (which I assumed is at least 80% of the use cases), ``endpoint`` should not be set. The template macro will determine it automatically via ``request.endpoint``.

If you are passing in a *different* endpoint, there's no guarantee that the view arguments will be a good fit then. If they are, you should be passing them in manually.

So either go full-auto:

```jinja2
{{render_pagination(my_pagination)}}
```

or pass both parameter:

```jinja2
{{render_pagination(my_pagination, endpoint='some_other_endpoint', args=request.view_args)}}
```

I'm suspecting right now that you're passing in ``endpoint``, but not ``args``. Let me know whether or not that's the case please.

**Comment by spk** [comment]
Yes you are right, I did not notice that. Thanks !
