### ISSUE TITLE
"No RECAPTCHA_PRIVATE_KEY config set" in sample_application

### ISSUE THREAD

**Issue by srlopez** [mbr/flask-bootstrap#95]
This is the last error line.
File "D:\Dev\Flask\project\venv\lib\site-packages\flask_wtf\recaptcha\validators.py", line 56, in _validate_recaptcha
raise RuntimeError("No RECAPTCHA_PRIVATE_KEY config set")

I think you need to add this key to the config in then sampla_application

**Comment by mbr** [comment]
It's not meant to be submitted. It's a very crappy sample application =).

**Comment by HellerCommaA** [comment]
@srlopez You can set a new key with app.config['RECAPTCHA_PUBLIC_KEY'] = 'YOUR_KEY_HERE'

**Comment by mbr** [comment]
I think I'll close this. My apologies if it caused a lot confusion =/.
