### ISSUE TITLE
Don't limit media to screen when importing bootstrap.css

### ISSUE THREAD

**Issue by pachi** [mbr/flask-bootstrap#96]
The base template limits the css stylesheet to screen media, but bootstrap also defines styles for print media and users could override the default styles if they wish to. Keeping out printed media means the user needs to do a new stylesheet declaration with the right media (duplicating the already downloaded contents), or changing the package (flask-bootstrap) provided base.html templante, which are both suboptimal solutions.

Could the media="screen" attribute in the base.html template could be changed to media="all"?

**Comment by mbr** [comment]
That sounds reasonable. The ``media`` is a relic from older Bootstrap versions.
