### ISSUE TITLE
Issue #39 is back

### ISSUE THREAD

**Issue by hordeim** [mbr/flask-bootstrap#97]
I believe that issue #39 is back as the code shows 

    {% macro quick_form(form,
                    action=".",
                    method="post",

The fix is to remove the .:

      {% macro quick_form(form,
                    action="",
                    method="post",

**Comment by mbr** [comment]
This should settle it.  I really wanted the form to submit to the current page by default, however an empty string would evaluate as ``False`` inside the template and not output any ``action`` attribute.

c207420 should fix this once and for all.
